/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IGaiaDividendDistributor } from "./IGaiaDividendDistributor";
export type { IWETH } from "./IWETH";
