/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as standards from "./standards";
export type { standards };
export type { GaiaGenesis } from "./GaiaGenesis";
export type { GaiaStableDAO } from "./GaiaStableDAO";
export type { GaiaSupernova } from "./GaiaSupernova";
