/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC721G } from "./IERC721G";
export type { IGaiaStableDAOMinter } from "./IGaiaStableDAOMinter";
export type { ISinglePool } from "./ISinglePool";
