/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC721G } from "./ERC721G";
export type { ERC721GURIStorage } from "./ERC721GURIStorage";
export type { IERC721G } from "./IERC721G";
export type { IERC721GURIStorage } from "./IERC721GURIStorage";
